examples: dataflow: execution environments: Use run_dataflow custom inputs failing
Traceback (most recent call last):
  File "/home/pdxjohnny/Documents/python/dffml/dffml/df/memory.py", line 1203, in run_dispatch
    outputs = await self.run(
  File "/home/pdxjohnny/Documents/python/dffml/dffml/df/memory.py", line 1168, in run
    return await self.run_no_retry(ctx, octx, operation, inputs)
  File "/home/pdxjohnny/Documents/python/dffml/dffml/df/memory.py", line 1146, in run_no_retry
    outputs = await opctx.run(inputs)
  File "/home/pdxjohnny/Documents/python/dffml/dffml/operation/dataflow.py", line 215, in run
    return await self.run_custom(inputs)
  File "/home/pdxjohnny/Documents/python/dffml/dffml/operation/dataflow.py", line 205, in run_custom
    raise InvalidCustomRunDataFlowOutputs(
dffml.operation.dataflow.InvalidCustomRunDataFlowOutputs: {'name': 'username_type', 'primitive': 'string'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pdxjohnny/Documents/python/dffml/examples/dataflow/execution_environments.py", line 149, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pdxjohnny/Documents/python/dffml/examples/dataflow/execution_environments.py", line 144, in main
    async for ctx, result in dffml.run(DATAFLOW):
  File "/home/pdxjohnny/Documents/python/dffml/dffml/high_level/dataflow.py", line 182, in run
    async for ctx, results in ctx.run(*input_sets, strict=strict):
  File "/home/pdxjohnny/Documents/python/dffml/dffml/df/memory.py", line 1588, in run
    raise exception
  File "/home/pdxjohnny/Documents/python/dffml/dffml/df/memory.py", line 1740, in run_operations_for_ctx
    raise OperationException(
dffml.df.base.OperationException: remote({'username': username_type}): {'username': 'World'}

Signed-off-by: John Andersen <johnandersenpdx@gmail.com>